# Form implementation generated from reading ui file 'new_window.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(525, 438)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ChatHystory = QtWidgets.QTextBrowser(parent=Dialog)
        self.ChatHystory.setObjectName("ChatHystory")
        self.verticalLayout.addWidget(self.ChatHystory)
        self.MyText = QtWidgets.QTextEdit(parent=Dialog)
        self.MyText.setObjectName("MyText")
        self.verticalLayout.addWidget(self.MyText)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.messageButton = QtWidgets.QPushButton(parent=Dialog)
        self.messageButton.setObjectName("messageButton")
        self.verticalLayout_2.addWidget(self.messageButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.messageButton.setText(_translate("Dialog", "PushButton"))
